### ISSUE TITLE
bitrise share start failing

### ISSUE THREAD

**Issue by realappie** [bitrise-io/bitrise-steplib#2619] opened 2020-08-05 17:55 UTC
I am running the `bitrise share start -c` command with a fork of this repository as input and I keep getting the following error

"FATA[19:52:45] Failed to save step spec, error: Failed to walk through path, error: not supported key found in options: is_sensitive "

A lot of steps in this repository use the `is_sensitive` option, but I am not sure what I should do about it. I just want to publish my step 😅 

I am using bitrise cli version `1.42.0` 

My fork can be found at https://github.com/realappie/bitrise-steplib

**Comment by mjones-droid** [comment] 2020-09-09 13:45
This is a duplicate of https://github.com/bitrise-io/bitrise/issues/733. Responding on that issue.

**Closed** 2021-04-09 14:11 UTC
